# Generated by Django 4.2.2 on 2023-06-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
