# Generated by Django 4.2.2 on 2023-06-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
